/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaptionProject {
  'title' : string,
  'thumbnailUrl' : [] | [string],
  'createdAt' : Time,
  'language' : string,
  'captions' : Array<CaptionSegment>,
  'videoUrl' : [] | [string],
}
export interface CaptionRequest { 'videoBlobId' : string, 'language' : string }
export interface CaptionSegment {
  'end' : bigint,
  'text' : string,
  'start' : bigint,
}
export interface RazorpayPaymentVerification {
  'signature' : string,
  'orderId' : string,
  'paymentId' : string,
}
export interface TemporalCaptionProject {
  'deletionTime' : Time,
  'project' : CaptionProject,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'coins' : bigint,
  'photoUrl' : [] | [string],
  'email' : string,
  'isPro' : boolean,
  'proExpiry' : [] | [Time],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCaptionProject' : ActorMethod<
    [string, [] | [string], Array<CaptionSegment>, [] | [string], string],
    undefined
  >,
  'createRazorpayOrder' : ActorMethod<[bigint, string], [] | [string]>,
  'deleteCaptionProject' : ActorMethod<[string], undefined>,
  'deleteCaptionProjectWithCooldown' : ActorMethod<[string], undefined>,
  'generateCaptions' : ActorMethod<[CaptionRequest], Array<CaptionSegment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLibrary' : ActorMethod<[], Array<CaptionProject>>,
  'getProject' : ActorMethod<[string], [] | [CaptionProject]>,
  'getTemporaryProjects' : ActorMethod<[], Array<TemporalCaptionProject>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyRazorpayPayment' : ActorMethod<[RazorpayPaymentVerification], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];