/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CaptionSegment = IDL.Record({
  'end' : IDL.Nat,
  'text' : IDL.Text,
  'start' : IDL.Nat,
});
export const CaptionRequest = IDL.Record({
  'videoBlobId' : IDL.Text,
  'language' : IDL.Text,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'coins' : IDL.Nat,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Text,
  'isPro' : IDL.Bool,
  'proExpiry' : IDL.Opt(Time),
});
export const CaptionProject = IDL.Record({
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'language' : IDL.Text,
  'captions' : IDL.Vec(CaptionSegment),
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const TemporalCaptionProject = IDL.Record({
  'deletionTime' : Time,
  'project' : CaptionProject,
});
export const RazorpayPaymentVerification = IDL.Record({
  'signature' : IDL.Text,
  'orderId' : IDL.Text,
  'paymentId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCaptionProject' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(CaptionSegment),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(IDL.Text)],
      [],
    ),
  'deleteCaptionProject' : IDL.Func([IDL.Text], [], []),
  'deleteCaptionProjectWithCooldown' : IDL.Func([IDL.Text], [], []),
  'generateCaptions' : IDL.Func(
      [CaptionRequest],
      [IDL.Vec(CaptionSegment)],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLibrary' : IDL.Func([], [IDL.Vec(CaptionProject)], ['query']),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(CaptionProject)], ['query']),
  'getTemporaryProjects' : IDL.Func(
      [],
      [IDL.Vec(TemporalCaptionProject)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyRazorpayPayment' : IDL.Func(
      [RazorpayPaymentVerification],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CaptionSegment = IDL.Record({
    'end' : IDL.Nat,
    'text' : IDL.Text,
    'start' : IDL.Nat,
  });
  const CaptionRequest = IDL.Record({
    'videoBlobId' : IDL.Text,
    'language' : IDL.Text,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'coins' : IDL.Nat,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Text,
    'isPro' : IDL.Bool,
    'proExpiry' : IDL.Opt(Time),
  });
  const CaptionProject = IDL.Record({
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'language' : IDL.Text,
    'captions' : IDL.Vec(CaptionSegment),
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const TemporalCaptionProject = IDL.Record({
    'deletionTime' : Time,
    'project' : CaptionProject,
  });
  const RazorpayPaymentVerification = IDL.Record({
    'signature' : IDL.Text,
    'orderId' : IDL.Text,
    'paymentId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCaptionProject' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(CaptionSegment),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
    'deleteCaptionProject' : IDL.Func([IDL.Text], [], []),
    'deleteCaptionProjectWithCooldown' : IDL.Func([IDL.Text], [], []),
    'generateCaptions' : IDL.Func(
        [CaptionRequest],
        [IDL.Vec(CaptionSegment)],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLibrary' : IDL.Func([], [IDL.Vec(CaptionProject)], ['query']),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(CaptionProject)], ['query']),
    'getTemporaryProjects' : IDL.Func(
        [],
        [IDL.Vec(TemporalCaptionProject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyRazorpayPayment' : IDL.Func(
        [RazorpayPaymentVerification],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };